```python
print(TestCaseTest("testTemplateMethod").run().summary())
print(TestCaseTest("testResult").run().summary())
print(TestCaseTest("testFailedResult").run().summary())
print(TestCaseTest("testFailedResultFormatting").run().summary())
```

맨 아래에 있는 테스트 실행 코드들이다 비참하다…

테스트들을 모아서 한 번에 실행할 수 있는 기능을 원한다 (테스트를 한 번에 하나씩만 실행시킨다면 테스트가 독립적으로 돌아가도록 만들기 위해 고생하는 건 별 의미가 없다)

TestSuite를 구현하면 컴포지트 패턴의 순수한 예제를 제공할 수 있다

TestSuite를 만들고 거기에 테스트를 몇 개 넣은 다음 이것을 모두 실행하고 그 결과를 얻어낼 것이다

TestCastTest

```python
		def testSuite(self):
        suite = TestSuite()
        suite.add(WasRun("testMethod"))
        suite.add(WasRun("testBrokenMethod"))
        result = suite.run()
        assert "2 run, 1 failed" == result.summary()
```

(new) TestSuite

```python
class TestSuite:
    def __init__(self):
        self.tests = []

    def add(self, test):
        self.tests.append(test)

    def run(self):
        result = TestResult()
        for test in self.tests:
            test.run(result)
        return result
```

문제가 있다

컴포지트 패턴으로 이 것을 구현하려고하는 중에 컴포지트의 제약 조건이 하나 생각났다
컴포지트의 주요 제약 중 하나는 컬렉션이 하나의 개별 아이템인 것처럼 반응해야 한다는 것이다

- 컴포지트 패턴

  https://mygumi.tistory.com/343

  https://readystory.tistory.com/131


TestCaseTest

```python
class TestCaseTest(TestCase):
    def testTemplateMethod(self):
        test = WasRun("testMethod")
        test.run()
        assert "setUp testMethod tearDown " == test.log

    def testResult(self):
        test = WasRun("testMethod")
        result = test.run()
        assert "1 run, 0 failed" == result.summary()

    def testFailedResult(self):
        test = WasRun("testBrokenMethod")
        result = test.run()
        assert "1 run, 1 failed" == result.summary()

    def testFailedResultFormatting(self):
        result = TestResult()
        result.testStarted()
        result.testFailed()
        assert "1 run, 1 failed" == result.summary()

    def testSuite(self):
        suite = TestSuite()
        suite.add(WasRun("testMethod"))
        suite.add(WasRun("testBrokenMethod"))
        result = TestResult()
        suite.run(result)
        assert "2 run, 1 failed" == result.summary()
```

TestCase

```python
class TestCase:
    def __init__(self, name):
        self.name = name

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def run(self, result):
        result.testStarted()
        self.setUp()
        try:
            method = getattr(self, self.name)
            method()
        except():
            result.testFailed()
        self.tearDown()
```

TestSuite

```python
class TestSuite:
    def __init__(self):
        self.tests = []

    def add(self, test):
        self.tests.append(test)

    def run(self, result):
        for test in self.tests:
            test.run(result)
```

main

```python
suite = TestSuite()
suite.add(TestCaseTest("testTemplateMethod"))
suite.add(TestCaseTest("testResult"))
suite.add(TestCaseTest("testFailedResultFormatting"))
suite.add(TestCaseTest("testFailedResult"))
suite.add(TestCaseTest("testSuite"))
result = TestResult()
suite.run(result)
print(result.summary())
```

**테스트 여러 개 실행하기**

위 코드로 실행을하면 실행이 안된다 나머지 테스트들에 result 인자가 없기 때문이다 돌아가게 수정하자

```python
class TestCaseTest(TestCase):
    def testTemplateMethod(self):
        result = TestResult()
        test = WasRun("testMethod")
        test.run(result)
        assert "setUp testMethod tearDown " == test.log

    def testResult(self):
        result = TestResult()
        test = WasRun("testMethod")
        result = test.run(result)
        assert "1 run, 0 failed" == result.summary()

    def testFailedResult(self):
        result = TestResult()
        test = WasRun("testBrokenMethod")
        result = test.run(result)
        assert "1 run, 1 failed" == result.summary()

    def testFailedResultFormatting(self):
        result = TestResult()
        result.testStarted()
        result.testFailed()
        assert "1 run, 1 failed" == result.summary()

    def testSuite(self):
        suite = TestSuite()
        suite.add(WasRun("testMethod"))
        suite.add(WasRun("testBrokenMethod"))
        result = TestResult()
        suite.run(result)
        assert "2 run, 1 failed" == result.summary()
```

중목이 어마어마하게 많다 이것은 정확히 setUp()으로 해결할 수 있는 문제이다

```python
class TestCaseTest(TestCase):
    def setUp(self):
        self.result = TestResult()

    def testTemplateMethod(self):
        test = WasRun("testMethod")
        test.run(self.result)
        assert "setUp testMethod tearDown " == test.log

    def testResult(self):
        test = WasRun("testMethod")
        result = test.run(self.result)
        assert "1 run, 0 failed" == result.summary()

    def testFailedResult(self):
        test = WasRun("testBrokenMethod")
        result = test.run(self.result)
        assert "1 run, 1 failed" == result.summary()

    def testFailedResultFormatting(self):
        self.result.testStarted()
        self.result.testFailed()
        assert "1 run, 1 failed" == self.result.summary()

    def testSuite(self):
        suite = TestSuite()
        suite.add(WasRun("testMethod"))
        suite.add(WasRun("testBrokenMethod"))
        suite.run(self.result)
        assert "2 run, 1 failed" == self.result.summary()
```

수많은 self 키워드들이 조금 지저분하긴 하지만 원래 그게 파이썬 문법이다.
이 목록의 나머지 항목은 당신이 새로 배운 TDD 기술을 이용해 직접 해볼 수 있게 남겨두겠다

- 테스트 메서드가 실패하더라도 tearDown 호출하기
- setUp 에러를 잡아서 보고하기
- TestCase 클래스에서 TestSuite 생성하기

우리는

- TestSuite를 위한 테스트를 작성했다
- 테스트를 통과시키지 못한 채 일부분만 구현하였다 이것은 ‘규칙’ 위반이다 만약 그 때 이걸 직접 발견했다면, 돈주머니에서 테스트 케이스 두 개를 공짜로 가져가도 좋다 테스트를 통과시키고 초록 막대 상태에서 리팩토링할 수 있게 할 간단한 가짜 구현이 있을 것 같긴 한데, 지금은 그게 뭔지 잘 떠오르지 않는다
- 아이템과 아이템의 모음(컴포지트)이 동일하게 작동할 수 있도록 run 메서드의 인터페이스를 변경하였고 마침내 테스트를 통과시켰다
- 공통된 셋업 코드를 분리했다
